scan_to_scan_filter_chain:
  ros__parameters:

    filter1:
      name: self_detection_filter_1
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -3.1416
        upper_angle: -2.85

    filter2:
      name: self_detection_filter_2
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -1.40
        upper_angle: -0.75

    filter3:
      name: self_detection_filter_3
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 0.75
        upper_angle: 1.40

    filter4:
      name: self_detection_filter_4
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 2.85
        upper_angle: 3.1416