slam_toolbox:
  ros__parameters:
    # -- Frames confirmées via view_frames --
    odom_frame: odom
    base_frame: base_footprint     # enfant direct de odom (pas base_link !)
    map_frame: map                  # sera créé par SLAM Toolbox lui-même
    scan_topic: /scan                # confirmé, frame_id = lidar_link

    # -- Simulation --
    use_sim_time: true

    # -- Résolution de la carte --
    resolution: 0.05                 # 5 cm par cellule
    max_laser_range: 20.0            # à ajuster si tu connais la vraie portée du LiDAR

    # -- Comportement du scan matching --
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2

    # -- Mode --
    mode: mapping                    # on construit la carte, pas seulement localisation